# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Balkan Archaeology 2016
email: balkan.arch.16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The doctoral student conference Balkan Archaeology 2016 conference will
  take place in Sofia, Bulgaria.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
